version: "2.1"
services:
  app:
    container_name: app       
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
        mongo:
          condition: service_healthy
  mongo:
    container_name: mongo
    image: mongo
    healthcheck:
          test: echo 'db.runCommand("ping").ok' 
          interval: 30s
          timeout: 30s
          retries: 5
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"